### ISSUE TITLE
zcompdump will fail to zcompile with some hostnames on macOS

### ISSUE THREAD

**Issue by segevfiner** [getantidote/use-omz#1]
```sh
❯ zrecompile -p '/Users/segevfiner/.cache/zsh/zcompdump-Segev’s MacBook Pro-5.9'
re-compiling /Users/segevfiner/.cache/zsh/zcompdump-Segev’s MacBook Pro-5.9.zwc: zrecompile:zcompile:133: can't write zwc file: /Users/segevfiner/.cache/zsh/zcompdump-Segev’s MacBook Pro-5.9.zwc
re-compiling /Users/segevfiner/.cache/zsh/zcompdump-Segev’s MacBook Pro-5.9.zwc: failed
```

Probably due to using `scutil --get ComputerName` which can include Unicode characters which zcompile seems to choke on... Probably need to escape them or maybe use `LocalHostName` instead?

**Comment by KapJI** [comment]
For anyone having the same issue. The issue is with unicode `’` symbol which macos adds to computer name.

You can replace it with regular `'` e.g.:
```
sudo scutil --set ComputerName "Segev's MacBook Pro"
```

This code is copied from main ohmyzsh repo, so it's better to create an issue here. It seems that using `ComputerName` isn't the best idea and `LocalHostName` is safer because of shouldn't have unicode symbols.

**Comment by mattmc3** [comment]
I'm slightly conflicted about this issue. On one hand, it's definitely a bug. On the other, it originates as an unreported bug in OMZ that `use-omz` inherits, albeit unintentionally.

The design goals of `use-omz` are to share code and mimic Oh-My-Zsh behaviors where possible to make it seamless to switch - even behaviors that aren't optimal. If I start tweaking use-omz to deviate too far from OMZ, it will become hard to maintain compatibility.

That said, this is a minor change that's probably better to make than to not, though a fix upstream would be way better. I'll go ahead and commit a fix, and if OMZ implements a different one in the future, I'll need to come back and update.

**Comment by segevfiner** [comment]
You can always submit the changes you made here as a PR to omz as well.
