### ISSUE TITLE
[oh-my-zsh] theme 'powerlevel10k' not found

### ISSUE THREAD

**Issue by smason-apex** [getantidote/use-omz#2]
I have the following in my `.zsh_plugins.txt`:

```
getantidote/use-omz
romkatv/powerlevel10k kind:fpath
```

and then in my `.zshrc`, I have (after the `antidote load` statement):
```
export ZSH_THEME='powerlevel10k'
autoload -Uz promptinit && promptinit && prompt ${ZSH_THEME}
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
```

When I load up my shell I get the warning: `[oh-my-zsh] theme 'powerlevel10k' not found`.  The prompt seems to be working fine.

If I remove the  `use-omz`, the prompt warning goes away but then some of the plugins I add start to fail becuase things like `$XDG_CACHE_HOME` aren't set.

Not sure how to proceed.

**Comment by mattmc3** [comment]
ZSH_THEME is a special variable for Oh-My-Zsh, so once you've set it, use-omz thinks you are trying to use an OMZ theme. It's relying on $ZSH/themes or $ZSH_CUSTOM/themes as the only paths where your theme can live, and obviously powerlevel10k isn't found there.

There's lots of different ways you could load powerlevel10k. The easiest thing to change would be to use a different variable name than the reserved ZSH_THEME. Another way would be to simply do this:

```
# .zsh_plugins.txt
getantidote/use-omz
romkatv/powerlevel10k
```

And...

```
# .zshrc
source /path/to/antidote.zsh
antidote load
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
```

**Comment by smason-apex** [comment]
Thanks for the detailed response. That clarifies things a whole bunch.

I tried your solution above but my prompt never loaded. I ended up not using `$ZSH_THEME` and that solved my problems.

Thanks for the tip and for antodote!
